/**
 * When running webpack, this script instructs it to generate the umd (for the browser) and commonjs (node)
 * configurations. The esm (ECMAScript module) version is generated by calling tsc directly so is not
 * handled by this script.
 */

const path = require("path");

/**
 * Creates a configuration
 * @param {string} libraryTarget Corresponds to output.libraryTarget
 */
function makeConfig(libraryTarget) {
  const outputPath = path.resolve(
    __dirname,
    "dist",
    libraryTarget === "commonjs" ? "node" : "umd"
  );

  return {
    mode: "production",
    entry: "./src/lrs.ts",
    devtool: "source-map",
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: "ts-loader",
          exclude: /node_modules/
        }
      ]
    },
    resolve: {
      extensions: [".tsx", ".ts", ".js"]
    },
    output: {
      path: outputPath,
      filename: "lrs.js",
      library: "wsdotArcgisRestLrs",
      libraryTarget,
      libraryExport: "default"
    },
    externals: /^@esri\/arcgis-rest/
  };
}

module.exports = ["umd", "commonjs"].map(makeConfig);
